yatube/about/urls.py
from django.urls import path
from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path
from . import views


app_name = 'posts'
urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/follow/',
         views.profile_follow, name='profile_follow'),
    path('profile/<str:username>/unfollow/',
         views.profile_unfollow, name='profile_unfollow'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/comment/',
         views.add_comment, name='add_comment'),
    path('follow/', views.follow_index, name='follow_index')
]

yatube/yatube/urls.py
from django.urls import path, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
    path('auth/', include('users.urls', namespace='users')),
    path('about/', include('about.urls', namespace='about')),
    path('auth/', include('django.contrib.auth.urls'))
]

handler404 = 'core.views.page_not_found'


if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model


User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200,
                             verbose_name='Название группы')
    slug = models.SlugField(unique=True, verbose_name='Относительный адрес')
    description = models.TextField(verbose_name='Описание группы')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Группа'
        verbose_name_plural = 'Группы'


class Post(models.Model):
    text = models.TextField(verbose_name='Текст поста',
                            help_text='Введите текст поста')
    pub_date = models.DateTimeField(auto_now_add=True,
                                    verbose_name='Дата публикации поста',
                                    db_index=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор поста'
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name='posts',
        verbose_name='Название группы',
        help_text='Группа, к которой будет относиться пост'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True)

    def __str__(self):
        return self.text[:15]

    class Meta:
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'
        ordering = ['-pub_date', 'author']


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Пост',
        help_text='Ваши комментарии')
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор комментария'
    )
    text = models.TextField(verbose_name='Текст комментария',
                            help_text='Ваши комменты')
    created = models.DateTimeField(auto_now_add=True,
                                   verbose_name='Дата комментария',
                                   db_index=True)

    def __str__(self):
        return self.text

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'
        ordering = ['-created']


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Подписчик'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Избранные авторы'
    )

    class Meta:
        verbose_name = 'Подписка'
        verbose_name_plural = 'Подписки'
        ordering = ['user']
        constraints = [models.UniqueConstraint(
            fields=['user', 'author'],
            name='unique_follow'),
            models.CheckConstraint(name='not_self_follow',
                                   check=~models.Q(user=models.F('author')))]

yatube/posts/forms.py
from django import forms
from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')
        labels = {'text': 'Творите',
                  'group': 'Выберите группу соратников',
                  'image': 'Картинка'}
        help_texts = {'text': 'И Лев Толстой здесь был',
                      'group': 'Но можете не выбирать',
                      'image': 'Выберите файл'}


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404
from django.views.decorators.cache import cache_page
from .models import Post, Group, User, Follow
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import redirect
from .forms import PostForm, CommentForm


NUMBER_OF_POSTS_PER_PAGE = 10


def paginator_page(request, posts):
    page_number = request.GET.get('page')
    paginator = Paginator(posts, NUMBER_OF_POSTS_PER_PAGE)
    return paginator.get_page(page_number)


@cache_page(20, key_prefix='index_page')
def index(request):
    template = 'posts/index.html'
    posts = Post.objects.select_related('author', 'group')
    page_obj = paginator_page(request, posts)
    following = False
    if request.user.is_authenticated:
        following = request.user.follower.exists()
    context = {'posts': posts,
               'page_obj': page_obj,
               'following': following}
    return render(request, template, context)


def group_posts(request, slug):
    template = 'posts/group_list.html'
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.select_related('author', 'group')
    page_obj = paginator_page(request, posts)
    context = {'group': group,
               'posts': posts,
               'page_obj': page_obj}
    return render(request, template, context)


def profile(request, username):
    template = 'posts/profile.html'
    author = get_object_or_404(User, username=username)
    posts = author.posts.all()
    page_obj = paginator_page(request, posts)
    following = False
    if request.user.is_authenticated and request.user != author:
        following = author.following.exists()
    context = {'posts': posts,
               'author': author,
               'page_obj': page_obj,
               'following': following}
    return render(request, template, context)


def post_detail(request, post_id):
    template = 'posts/post_detail.html'
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    comments = post.comments.select_related('author')
    context = {'post': post,
               'comments': comments,
               'form': form}
    return render(request, template, context)


@login_required
def post_create(request):
    template = 'posts/create_post.html'
    form = PostForm(request.POST or None, files=request.FILES or None)
    context = {'form': form}
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', username=request.user)
    return render(request, template, context)


@login_required
def post_edit(request, post_id):
    template = 'posts/create_post.html'
    post = get_object_or_404(Post, id=post_id)
    form = PostForm(request.POST or None,
                    files=request.FILES or None, instance=post)
    if request.user != post.author:
        return redirect('posts:post_detail', post_id=post_id)
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id=post_id)
    context = {'form': form,
               'post': post,
               'is_edit': True}
    return render(request, template, context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    posts = Post.objects.select_related(
        'author', 'group').filter(
        author__following__user=request.user)
    page_obj = paginator_page(request, posts)
    context = {'posts': posts,
               'page_obj': page_obj}
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    follower = Follow.objects.filter(user=request.user,
                                     author=author)
    if author != request.user and not follower.exists():
        Follow.objects.get_or_create(user=request.user,
                                     author=author)
    return redirect('posts:profile', username=author)


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    Follow.objects.filter(user=request.user,
                          author=author).delete()
    return redirect('posts:profile', username=username)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}

{% block title %}
      <title>
     {% if is_edit %}
     Редактировать запись
     {% else %}
     Добавить запись
     {% endif %}
      </title>
{% endblock %}

{% block content %}
  <body>
    <main>
      <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                  {% if is_edit %}
                    Редактировать пост
                  {% else %}
                    Добавить запись
                  {% endif %}
              </div>
              <div class="card-body">
                <form method="POST" enctype="multipart/form-data">
                  {% csrf_token %}
                  <div class="form-group row my-3 p-3">
                    <label for="id_text">
                      {{ form.text.label_tag }}
                      <span class="required text-danger" >*</span>
                    </label>
                    {{ form.text }}
                    <small id="id_text-help" class="form-text text-muted">
                      {{ form.text.help_text }}
                    </small>
                  </div>
                  <div class="form-group row my-3 p-3">
                    <label for="id_group">
                      {{ form.group.label_tag }}
                    </label>
                    <select name="group" class="form-control" id="id_group">
                      <option value="" selected>---------</option>
                      <option value= {{ form.group }}</option>
                    </select>
                    <small id="id_group-help" class="form-text text-muted">
                      {{ form.group.help_text }}
                    </small>
                  </div>
                  <div class="form-group row my-3 p-3">
                    <label for="id_image">
                      Картинка
                    </label>
                    <input type="file" name="image" accept="image/*" class="form-control" id="id_image">
                  </div>
                  <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary">
                      {% if is_edit %}
                       Редактировать пост
                      {% else %}
                       Добавить пост
                      {% endif %}
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>
  </body>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
<title>Избранное</title>
{% endblock %}
{% block content %}
<main>
  <div class="container py-5">
    <h1>Избранное</h1>
    <article>
    {% include 'posts/includes/switcher.html' %}
      {% for post in page_obj %}
        <ul>
          <li>
            Автор: {{ post.author.get_full_name }} <a href="{% url 'posts:profile' post.author.username %}">
                все посты пользователя</a>
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
        </ul>
          {% thumbnail post.image "400x200" crop="center" upscale=True as im %}
             <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
        <p>{{ post.text }}</p>
        {% if post.group %}
           <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы {{ post.group }} </a>
        {% endif %}
        {% if not forloop.last %}<hr>{% endif %}
      {% endfor %}
      {% include 'posts/includes/paginator.html' %}
    </article>
  </div>
</main>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
<title>Записи сообщества {{ group.title }}</title>
{% endblock %}
{% block content %}
<main>
  <div class="container py-5">
    <h1>{{ group.title }}</h1>
    <p>
      {{ group.description }}
    </p>
      {% for post in page_obj %}
        {% include 'posts/includes/post_list.html' %}
      {% if not forloop.last %}<hr>{% endif %}
      {% endfor %}
      {% include 'posts/includes/paginator.html' %}
  </div>
</main>
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load cache %}

{% block title %}
   <title> Последние обновления на сайте</title>
{% endblock %}

{% block content %}
   <div class="container py-5">
   <h1>Последние обновления на сайте</h1>
     {% if following %}
      {% include 'posts/includes/switcher.html' %}
     {% endif %}
   {% cache 20 index_page %}
     {% for post in page_obj %}
      {% include 'posts/includes/post_list.html' %}
      {% if post.group %}
        <li>
          <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
        </li>
      {% endif %}
      {% if not forloop.last %}<hr>{% endif %}
     {% endfor %}
   {% endcache %}
      {% include 'posts/includes/paginator.html' %}
   </div>
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load user_filters %}
{% load thumbnail %}
{% block title %}
  <title>Пост<{{ post.text|truncatechars:30 }} </title>
{% endblock %}
{% block content %}
  <body>
    <main>
      <div class="row">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
            {% if post.group %}
            <li class="list-group-item">
               Группа: {{ post.group }} <a href="{% url 'posts:group_list' post.group.slug %}">
              все записи группы </a><!-- Название группы -->
            </li>
            {% endif %}
            </li>
            <li class="list-group-item">
              Автор: {{ post.author.get_full_name }}<!--Лев Толстой-->
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора: <span> {{ post.author.posts.count }} </span>
            </li>
            <li class="list-group-item">
              <a href="{% url 'posts:profile' post.author.username %}">
                все посты пользователя {{ post.author.get_full_name }}
              </a>
            </li>
          </ul>
        </aside>
        <article class="col-12 col-md-9">
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
             <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
          <p>
            {{ post.text}}
          </p>
          {% if request.user == post.author %}
          <a class="btn btn-primary" href="{% url 'posts:post_edit' post.id %}" >
             Редактировать пост
          </a>
          {% endif %}
          {% if user.is_authenticated %}
            <div class="card my-4">
              <h5 class="card-header">Добавить комментарий:</h5>
              <div class="card-body">
                <form method="post" action="{% url 'posts:add_comment' post.id %}">
                  {% csrf_token %}
                  <div class="form-group mb-2">
                    {{ form.text|addclass:"form-control" }}
                  </div>
                    <button type="submit" class="btn btn-primary">Отправить</button>
                </form>
              </div>
            </div>
          {% endif %}
          {% for comment in comments %}
            <div class="media mb-4">
              <div class="media-body">
                <h5 class="mt-0">
                  <a href="{% url 'posts:profile' comment.author.username %}">
                  {{ comment.author.username }}
                  </a>
                </h5>
                <p>
                  {{ comment.text }}
                </p>
              </div>
            </div>
          {% endfor %}
        </article>
      </div>
    </main>
  </body>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
<title>Профайл пользователя {{ author.get_full_name }} </title>
{% endblock %}

{% block content %}
  <body>
    <main>
      <div class="container py-5">
        <h1>Все посты пользователя {{ author.get_full_name }} </h1>
        <h3>Всего постов: {{ author.posts.count }} </h3>
        {% if request.user != author  and request.user.is_authenticated %}
          {% if following %}
            <a class="btn btn-lg btn-light"
            href="{% url 'posts:profile_unfollow' author.username %}" role="button">
             Отписаться </a>
          {% else %}
            <a class="btn btn-lg btn-primary"
              href="{% url 'posts:profile_follow' author.username %}" role="button">
              Подписаться
            </a>
          {% endif %}
        {% endif %}
        <article>
          {% for post in page_obj %}
            <ul>
              <li>
                Автор: {{ author.get_full_name }}
              </li>
              <li>
                Дата публикации: {{ post.pub_date|date:"d E Y" }}<!-- 31 июля 1854 -->
              </li>
            </ul>
            <p>
             {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
               <img class="card-img my-2" src="{{ im.url }}">
             {% endthumbnail %}
              {{ post.text }}
            </p>
              <li>
                <a href="{% url 'posts:post_detail' post.id %}">подробная информация </a>
              </li>
              {% if post.group %}
                <li>
                  <a href="{% url 'posts:group_list' post.group.slug %}">
                  все записи группы {{ post.group }}
                  </a>
                </li>
               {% endif %}
              {% if not forloop.last %}<hr>{% endif %}
          {% endfor %}
          {% include 'posts/includes/paginator.html' %}
        </article>
      </div>
    </main>
  </body>
{% endblock %}